<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

/*
 * Automatically generated by Laravel auth. Leaved in case of future usage.
 */
class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}
